[project]
name = "pydantic-intro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "waseem-development", email = "hafizwaseemahmed2002@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.141.1",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "python-dotenv>=1.2.3",
    "uvicorn>=0.52.4",
]

[project.scripts]
pydantic-intro = "pydantic_intro:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
